image: node:8
cache:
  paths:
    - node_modules/
services:
  - redis:alpine
  - couchdb:1.6
stages:
  - test
  - deploy
variables:
  REDIS_URL: redis://redis:6379
  CLOUDANT_URL: http://couchdb:5984
mocha:
  stage: test
  script:
    - npm install
    - npm run cover
  artifacts:
    paths:
      - coverage/
  tags:
    - docker
pages:
  stage: deploy
  dependencies:
    - mocha
  script:
    - mv coverage/lcov-report public
  artifacts:
    paths:
      - public
  only:
    - master
