sudo: false
language: node_js
node_js:
  - "0.12"
services:
  - couchdb
  - redis-server
script: npm run cover
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate < coverage/lcov.info
